### ISSUE TITLE
Material on typeclasses in Scala

### ISSUE THREAD

**Issue by slentzen** [ktakagaki/hayabaya#21]
I'm looking for further reading material on Scala's type classes.
I've read Oderskys chapters on the topic, and the following video
https://www.youtube.com/watch?v=sVMES4RZF-8&feature=youtu.be

I am however not entirely sure what all of the applications of this feature is. The scala-lang.org website doesn't explicitly have any sections on typeclasses. What is another name for typeclasses, so I can Google for further information?

**Comment by ktakagaki** [comment]
It's not that hard to grasp once you see it a couple of times in action.
Then, you'll realize that what he's saying is quite straight forward and
makes a lot of sense. It's just as he says, you can inject functionality
for an object into your code (without touching the object itself). As he
says, it's especially useful with ```implicit``` resolution.

If you want the theory, I guess you should go towards Haskell reading,
although it's probably tough if you don't have exposure to that kind of
language before. Sorry, don't know any other resources. There are probably
no clear synonyms.




*Kentaroh Takagaki, MD PhD (高垣 堅太郎)*
     Group Leader, AG Neuro-Optics
     Department Systems Physiology of Learning
     Leibniz Institute for Neurobiology
     <kentaroh.takagaki@lin-magdeburg.de
<kentaroh.takagaki@ifn-magdeburg.de>>
     http://www.lin-magdeburg.de/en/ifn_mp.jsp?member=ktakagak&fc=T

**Comment by ktakagaki** [comment]
It's not that hard to grasp once you see it a couple of times in action. Then, you'll realize that what the video guy says is quite straight forward and makes a lot of sense. It's just as he says, you can inject functionality for an object into your code (without touching the object itself). As he says, it's especially useful with ```implicit``` resolution.

If you want the theory, I guess you should go towards Haskell reading, although it's probably tough if you don't have exposure to that kind of language before. Sorry, don't know any other resources. There are probably no clear synonyms.
