### ISSUE TITLE
Create SOP/Agree on standard procedure for colaborating

### ISSUE THREAD

**Issue by slentzen** [ktakagaki/hayabaya#24]
Agreee on a standard / And/or Standard Operating Procedure/Protocol for how to collaborate on GitHub.

New branches have been created on my Hayabaya repository which are preventing me from pushing own changes unless I do a Git rebase.

To avoid such future collissions, we should come up with a standard procedure for how we work together on each others repositories besides using pull requests.

We have already established our branching strategy as using the most commonly used topic branches and then do pull requests against another persons master branches. After target accepts the pull request, merges the changes into his branch the sender will fetch upstream and merge the new changes into his own branch. This is following the common way of doing things 

Collaboration workflows are outlined here in the [Git SCM Book](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows)

Now we just need to agree on a workflow for when working directly on another persons repository.

@ktakagaki

**Comment by ktakagaki** [comment]
I think perhaps that direct work on the other repository should be avoided in general, the PR process is probably easier to manage (although it leads to too many branches accumulating).

I've pruned down the branches which are no longer relevant in this repo, and converted them to tags.

**Comment by slentzen** [comment]
Thanks

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Slentzen Demian
slentzen@gmail.com
evenprime@tutanota.com

https://github.com/slentzen
https://de.linkedin.com/in/slentzen-demian-19997366

Get my Public PGP Key Here: http://pastebin.com/SSb3NGtS
</Signature>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWrxx2AAoJEHmWhfKhCnpK4joQAJMhbGEx4DtMd5LKee/q5dbp
Vy49Vo42bD0AZV51PLKvDMHoRthJAjT+s2fn5hX6rA2asaZP3Ne+nn+TyBoBf/cm
8p0Hr95IQMJ91KEEb+0C2setU3mA5eQnDcMRx5ahXXOQt/VAKyIdSiyLTUS5WA8R
qnCCrc9LXZLmMywg0tv1Zcy5/3SaCERWY/gY3perBhn1zGkSKR0avBR6SzafJKaz
kDKmj0mXe3VgyUEItPKTdX3cQWxs9mOzOiyICcid/VJ5Ykuxp70KAJFu2npGvrFs
ZTrENI8/wgZvZNWGyHTXM3cq4JrH3mCVXuKBpbLxD9Rr8vrPRnKjHtKFT1+Ryw1i
MiK8W0zays+M5/nOpnxe6nOKQ8Q/edFMM+pJ/IYWpogKjlEFBlWu3bIhzj5DAxHL
OqNACnXu7XFGkvDV14VhWMu2wOfYkLDHCWXzDRoWAy6KglOXxtw5/oHBuVuI+rjk
9WEwiXWLHANpe4rjqhMlBWoFjZ4eSyTbwa2O7JI31ycVB5G3syFjENBuE7DrktQy
m11ILH1vMEcFKg+5+o8y1uEvyLPiU7EML2Vpsjl7yBb4sLR99rPa3/JWCrkGjOjQ
t2qjVYj/1l4NaZglpHkUed+bh24GOjPABopfoSo2eOPMecfrtDXu0rseL4P/zIQF
7bmul3saTtntgHhO7S1j
=l8Fs
-----END PGP SIGNATURE-----
