### ISSUE TITLE
prune dead branches

### ISSUE THREAD

**Issue by slentzen** [ktakagaki/hayabaya#25]
Below I have shown the branches that I see when running git branch. To my knowledge, several of the branches are now no longer of any relevance and can be deleted, then I can run git prune to delete the dead references.
```{bash}
[cain@x51 hayabaya]$ (master) git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/TopicAugust05
  remotes/origin/caseclasses
  remotes/origin/dev
  remotes/origin/extra
  remotes/origin/kentaScala
  remotes/origin/kentatemp
  remotes/origin/master
  remotes/origin/meeting150522
  remotes/origin/simplifyLoopKenta
  remotes/origin/test190415
  remotes/origin/topic26
  remotes/upstream/TopicAugust05
  remotes/upstream/extra
  remotes/upstream/kentaScala
  remotes/upstream/kentaTestEnum160129
  remotes/upstream/kentatemp
  remotes/upstream/master
  remotes/upstream/meeting150522
  remotes/upstream/simplifyLoopKenta
  remotes/upstream/test190415
  remotes/upstream/topic26
```

**Comment by ktakagaki** [comment]
Feel free to prune away at hayabaya. I'll still have my local branches too.

**Comment by slentzen** [comment]
I can't prune your remote branches can I? Well maybe I can because I'm
added as a collaborator. But I don't feel entirely comfortable edeting and
deleting another persons branches on his repository.

But if you would prefer it that way, sure I can do it. I will delete the
remote branches on your repository and then issue a git prune command
locally on my own computer so I can delete the dead references. If I
accidently delete any branch I shouldn't have, you can send me a message
stating which one I must leave alone and then push your local branch back
up on the remote repository


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Slentzen Demian
slentzen@gmail.com
evenprime@tutanota.com

https://github.com/slentzen
https://de.linkedin.com/in/slentzen-demian-19997366

Get my Public PGP Key Here: http://pastebin.com/SSb3NGtS
</Signature>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWrxx2AAoJEHmWhfKhCnpK4joQAJMhbGEx4DtMd5LKee/q5dbp
Vy49Vo42bD0AZV51PLKvDMHoRthJAjT+s2fn5hX6rA2asaZP3Ne+nn+TyBoBf/cm
8p0Hr95IQMJ91KEEb+0C2setU3mA5eQnDcMRx5ahXXOQt/VAKyIdSiyLTUS5WA8R
qnCCrc9LXZLmMywg0tv1Zcy5/3SaCERWY/gY3perBhn1zGkSKR0avBR6SzafJKaz
kDKmj0mXe3VgyUEItPKTdX3cQWxs9mOzOiyICcid/VJ5Ykuxp70KAJFu2npGvrFs
ZTrENI8/wgZvZNWGyHTXM3cq4JrH3mCVXuKBpbLxD9Rr8vrPRnKjHtKFT1+Ryw1i
MiK8W0zays+M5/nOpnxe6nOKQ8Q/edFMM+pJ/IYWpogKjlEFBlWu3bIhzj5DAxHL
OqNACnXu7XFGkvDV14VhWMu2wOfYkLDHCWXzDRoWAy6KglOXxtw5/oHBuVuI+rjk
9WEwiXWLHANpe4rjqhMlBWoFjZ4eSyTbwa2O7JI31ycVB5G3syFjENBuE7DrktQy
m11ILH1vMEcFKg+5+o8y1uEvyLPiU7EML2Vpsjl7yBb4sLR99rPa3/JWCrkGjOjQ
t2qjVYj/1l4NaZglpHkUed+bh24GOjPABopfoSo2eOPMecfrtDXu0rseL4P/zIQF
7bmul3saTtntgHhO7S1j
=l8Fs
-----END PGP SIGNATURE-----

**Comment by ktakagaki** [comment]
I thought you could, but I've gone ahead and converted to tags.
